// <auto-generated />
namespace WebBanSach_2_0.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class bigupdatedbv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bigupdatedbv2));
        
        string IMigrationMetadata.Id
        {
            get { return "202002130653052_big-update-dbv2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
