// <auto-generated />
namespace WebBanSach_2_0.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class SP_DO_NOT_DELETE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SP_DO_NOT_DELETE));
        
        string IMigrationMetadata.Id
        {
            get { return "202007170851379_SP_DO_NOT_DELETE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
