// <auto-generated />
namespace WebBanSach_2_0.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class bigupdatedbv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bigupdatedbv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202002130619396_big-update-dbv1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
